#!/usr/bin/env python3
"""
AlphaFold structure prediction script for Progen2 sequences.

This script provides a Python interface to run AlphaFold on sequences
generated by the Progen2 pipeline.

Usage:
    python scripts/alphafold_predict.py <fasta_file> [--output-dir OUTPUT_DIR] [--max-sequences N]

Example:
    python scripts/alphafold_predict.py runs/run_20251230_progen2_medium_r1_test/candidates/candidates.ranked.fasta
"""

import sys
import os
import argparse
import subprocess
from pathlib import Path
from typing import Optional


def check_alphafold_available() -> tuple[str, Optional[str]]:
    """
    Check if AlphaFold is available (Docker or local).
    
    Returns:
        (mode, path) where mode is 'docker', 'local', or 'none'
    """
    # Check Docker
    try:
        result = subprocess.run(
            ['docker', 'ps'],
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            # Check for AlphaFold image
            result = subprocess.run(
                ['docker', 'images', 'alphafold'],
                capture_output=True,
                text=True
            )
            if 'alphafold' in result.stdout.lower():
                return 'docker', None
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    
    # Check local installation
    alphafold_path = Path(os.environ.get('ALPHAFOLD_PATH', '/opt/alphafold'))
    if alphafold_path.exists() and (alphafold_path / 'run_alphafold.py').exists():
        return 'local', str(alphafold_path)
    
    return 'none', None


def run_alphafold_docker(
    fasta_file: Path,
    output_dir: Path,
    db_path: Optional[str] = None
) -> None:
    """Run AlphaFold via Docker."""
    import os
    
    db_path = db_path or os.environ.get('ALPHAFOLD_DB_PATH', '/data/alphafold_db')
    
    cmd = [
        'docker', 'run',
        '--rm',
        '-v', f'{Path.cwd()}:/data',
        '-v', f'{db_path}:/alphafold_db',
        'alphafold',
        'python', '/app/run_alphafold.py',
        f'--fasta_paths=/data/{fasta_file}',
        f'--output_dir=/data/{output_dir}',
        '--data_dir=/alphafold_db',
        '--max_template_date=2024-01-01',
        '--model_preset=monomer',
        '--db_preset=full_dbs'
    ]
    
    print(f"Running: {' '.join(cmd)}")
    subprocess.run(cmd, check=True)


def run_alphafold_local(
    fasta_file: Path,
    output_dir: Path,
    alphafold_path: str,
    db_path: Optional[str] = None
) -> None:
    """Run AlphaFold locally."""
    import os
    
    db_path = db_path or os.environ.get('ALPHAFOLD_DB_PATH', '/data/alphafold_db')
    
    cmd = [
        sys.executable,
        str(Path(alphafold_path) / 'run_alphafold.py'),
        f'--fasta_paths={fasta_file}',
        f'--output_dir={output_dir}',
        f'--data_dir={db_path}',
        '--max_template_date=2024-01-01',
        '--model_preset=monomer',
        '--db_preset=full_dbs'
    ]
    
    print(f"Running: {' '.join(cmd)}")
    subprocess.run(cmd, check=True)


def limit_fasta_sequences(fasta_file: Path, max_sequences: int, output_file: Path) -> Path:
    """Limit FASTA file to first N sequences."""
    count = 0
    with open(fasta_file) as f_in, open(output_file, 'w') as f_out:
        for line in f_in:
            if line.startswith('>'):
                count += 1
                if count > max_sequences:
                    break
            f_out.write(line)
    return output_file


def main():
    parser = argparse.ArgumentParser(
        description="Run AlphaFold structure prediction on Progen2 sequences",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Predict structures for top candidates
  python scripts/alphafold_predict.py runs/run_20251230_progen2_medium_r1_test/candidates/candidates.ranked.fasta
  
  # Limit to first 5 sequences
  python scripts/alphafold_predict.py candidates.ranked.fasta --max-sequences 5
  
  # Specify custom output directory
  python scripts/alphafold_predict.py candidates.ranked.fasta --output-dir runs/alphafold_predictions
        """
    )
    
    parser.add_argument('fasta_file', type=Path, help='Input FASTA file with sequences')
    parser.add_argument('--output-dir', type=Path, default=None,
                       help='Output directory (default: runs/YYYY-MM-DD_alphafold)')
    parser.add_argument('--max-sequences', type=int, default=10,
                       help='Maximum number of sequences to process (default: 10)')
    parser.add_argument('--db-path', type=str, default=None,
                       help='Path to AlphaFold databases (overrides ALPHAFOLD_DB_PATH)')
    
    args = parser.parse_args()
    
    # Check input file
    if not args.fasta_file.exists():
        print(f"Error: FASTA file not found: {args.fasta_file}")
        sys.exit(1)
    
    # Set output directory
    if args.output_dir is None:
        from datetime import datetime
        args.output_dir = Path(f"runs/{datetime.now().strftime('%Y-%m-%d')}_alphafold")
    
    args.output_dir.mkdir(parents=True, exist_ok=True)
    
    # Count sequences
    num_sequences = sum(1 for line in open(args.fasta_file) if line.startswith('>'))
    print(f"Found {num_sequences} sequences in {args.fasta_file}")
    
    # Limit sequences if needed
    fasta_to_use = args.fasta_file
    if num_sequences > args.max_sequences:
        print(f"Limiting to first {args.max_sequences} sequences")
        fasta_to_use = args.output_dir / 'input_limited.fasta'
        limit_fasta_sequences(args.fasta_file, args.max_sequences, fasta_to_use)
    
    # Check AlphaFold availability
    mode, path = check_alphafold_available()
    
    if mode == 'none':
        print("Error: AlphaFold not found")
        print("\nOptions:")
        print("1. Use ColabFold (easier): python scripts/colabfold_predict.py")
        print("2. Install AlphaFold: https://github.com/deepmind/alphafold")
        print("3. Use AlphaFold via Docker")
        sys.exit(1)
    
    # Run AlphaFold
    print(f"\nRunning AlphaFold ({mode})...")
    print(f"Input: {fasta_to_use}")
    print(f"Output: {args.output_dir}\n")
    
    try:
        if mode == 'docker':
            run_alphafold_docker(fasta_to_use, args.output_dir, args.db_path)
        elif mode == 'local':
            run_alphafold_local(fasta_to_use, args.output_dir, path, args.db_path)
        
        print(f"\n✓ AlphaFold prediction complete!")
        print(f"Results saved to: {args.output_dir}")
        
    except subprocess.CalledProcessError as e:
        print(f"\nError running AlphaFold: {e}")
        sys.exit(1)
    except KeyboardInterrupt:
        print("\n\nInterrupted by user")
        sys.exit(1)


if __name__ == '__main__':
    import os
    main()

